market/conversation/urls.py
from django.urls import path
from . import views

app_name='conversation'


urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name="new"),
    path('<int:pk>/',views.detail ,name="detail"),
    path('',views.inbox,name="inbox"),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('',views.index,name="home"),
    path('contact',views.contact,name="contact"),
    path('signup/',views.signup,name="signup"),
    path('logout/',views.logout_user,name="logout"),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm),name="login")
]

market/item/urls.py
from django.urls import path
from .import views


app_name = 'item'
urlpatterns = [
    path('',views.items,name="items"),
    path('new/',views.new,name="new_item"),
    path('<int:pk>/', views.detail,name="detail"),
    path('<int:pk>/delete/', views.delete,name="delete"),
    path('<int:pk>/edit/', views.edit,name="edit"),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

market/item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'form-control border border-dark-subtle mt-1'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','price','image')

        widgets = {
            'category':forms.Select(attrs={'class':INPUT_CLASSES}),
            'name':forms.TextInput(attrs={'class':INPUT_CLASSES}),
            'description':forms.Textarea(attrs={'class':INPUT_CLASSES}),
            'price':forms.TextInput(attrs={'class':INPUT_CLASSES}),
            'image':forms.FileInput(attrs={'class':INPUT_CLASSES})
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','price','image','is_sold')

        widgets = {
            'name':forms.TextInput(attrs={'class':INPUT_CLASSES}),
            'description':forms.Textarea(attrs={'class':INPUT_CLASSES}),
            'price':forms.TextInput(attrs={'class':INPUT_CLASSES}),
            'image':forms.FileInput(attrs={'class':INPUT_CLASSES})
        }

market/item/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Item,Category
from .forms import NewItemForm,EditItemForm
# Create your views here.

def items(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    if category_id:
        items = items.filter(category_id = category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query) )

    return render(request, 'item/items.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id)
    })



def detail(request, pk):
    item = Item.objects.get(id=pk)
    related_items = Item.objects.filter(category = item.category, is_sold = False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item':item,
        'related_items':related_items
    })


@login_required
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit = False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm()
        return render(request,'item/additem.html',{
            'form':form
            })

    return render(request,'item/additem.html',{
        'form':form
    })


@login_required
def edit(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance=item)
        return render(request,'item/additem.html',{
            'form':form
            })

    return render(request,'item/additem.html',{
        'form':form
    })


@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect("dashboard:index")

market/item/templates/item/additem.html
{% extends 'core/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3 my-4">
    <h1 class="text-center text-primary-emphasis">New Item</h1>
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors or form.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Cannot add Item try again
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success w-25 mt-3 py-2">Submit</button>
        <a href="{% url 'core:home' %}", class="btn btn-secondary mt-3 px-3 py-2">Back</a>
    </form>
</div>

{% endblock %}

market/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block content %}
<div class="d-flex  mt-4">
    <a href="{% url 'core:home' %}">
        <i class="fa-sharp fa-solid fa-circle-arrow-left fs-1 mx-4 text-dark"></i>
    </a>
<div class="mb-3 mx-auto" style="max-width:80%">
    <div class="d-flex">
      <div class="col-md-4 action-checkbox">
        <img src={{ item.image.url }} class="img-fluid rounded-2 h-100 ">
      </div>
      <div class="col-md-8">
        <div class="bg-secondary-subtle py-3 px-4 ms-3 h-100 rounded-2 d-flex flex-column">
          <h2 class="card-title"><b>{{item.name}}</b></h2>
          <p class="card-title fs-4"><b>Price:</b> ${{ item.price }}</p>
          {% if item.description %}
            <p class="card-text mt-2"><b>Description:</b><br>{{ item.description }}</p>
          {% endif %}
          {% if request.user == item.created_by %}
          <div class="mt-auto">
                <div>
                    <a href="{% url 'item:edit' item.id %}" class="btn btn-secondary mb-3 me-2 w-25">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="btn btn-danger mb-3 me-2 w-25">Delete</a>
                </div>
                <p class="card-text text-secondary border-top border-secondary-subtle pt-2 mt-auto">You are the owner of this Item</p>
            </div>
          {% else %}
            <div class="mt-auto">
                <p class="card-text"><small class="text-body-secondary">Seller: {{ item.created_by.username }}</small></p>
                <div>
                    <button class="btn btn-success btn-lg w-25">Purchase</button>
                    <a href="{% url 'conversation:new' item.id %}" class="btn btn-info btn-lg">Contact Seller</a>
                </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% if related_items %}
    <div class="w-auto my-4 mx-4 px-5 py-5 rounded-3">
        <h2 class="fs-4 text-center mb-4">Related Items</h2>
        <div class="row row-cols-1 row-cols-md-3 g-4 ">
            {% for related_item in related_items %}
            <div class="col ">
                
                <div class="card h-auto" style="width: 18rem;">
                    <a href="{% url 'item:detail' related_item.id %}" class='text-decoration-none'>
                        <img src="{{ related_item.image.url }}" class="card-img-top w-100%" >
                        <div class="card-body">
                        <h5 class="card-title">{{ related_item.name }}</h5>
                        <h5 class="card-title text-secondary">${{ related_item.price }}</h5>
                        <a href="#" class="btn btn-success">Purchase</a>
                    </a>
                    
                </div>
            
                
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endif %}
{% endblock %}

market/item/templates/item/items.html
{% extends 'core/base.html' %}


{% block content %}
    <div class="d-flex my-4">
        <div class="pb-3 px-2 bg-secondary-subtle rounded-2 mx-3 w-25 d-flex flex-column" style="min-width:20%">
            <form method="GET" action="{% url 'item:items' %}">
                <input name="query" value="{{ query }}" class="form-control mt-2 mb-3 py-2" placeholder="Find a bed,bike or chair">
                <button class="btn btn-success">Search</button>
            </form>

            <p class="text-center fw-semibold mt-4 fs-5">Categories</p>
            <ul class="list-unstyled mx-2">
                {% for category in categories%}
                <li class="my-3">
                    <a class="text-dark text-decoration-none text-capitalize {% if category.id == category_id %}fw-semibold{% endif %}" href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>
            <div class="mt-auto">
            <p class="text-center fw-semibold fs-5" >Clear Filters</p>
            <a href="{% url 'item:items' %}" class="btn btn-warning px-4">Clear</a>
            </div>
        </div>
        <div>
            <div class="d-flex flex-wrap align-items-stretch">
                {% for item in items %}
                <div class="mx-3 mb-4">
                    <div class="card h-auto" style="width: 18rem;">
                        <a href="{% url 'item:detail' item.id %}" class='text-decoration-none'>
                            <img src="{{ item.image.url }}" class="card-img-top w-100%" >
                            <div class="card-body">
                                <h5 class="card-title">{{ item.name }}</h5>
                                <h5 class="card-title text-secondary">${{ item.price }}</h5>
                            </div> 
                        </a>      
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}