market/conversation/urls.py
from django.urls import path
from . import views

app_name='conversation'


urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name="new"),
    path('<int:pk>/',views.detail ,name="detail"),
    path('',views.inbox,name="inbox"),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('',views.index,name="home"),
    path('contact',views.contact,name="contact"),
    path('signup/',views.signup,name="signup"),
    path('logout/',views.logout_user,name="logout"),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm),name="login")
]

market/dashboard/urls.py
from django.urls import path
from . import views 


app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name="index"),
]

market/item/urls.py
from django.urls import path
from .import views


app_name = 'item'
urlpatterns = [
    path('',views.items,name="items"),
    path('new/',views.new,name="new_item"),
    path('<int:pk>/', views.detail,name="detail"),
    path('<int:pk>/delete/', views.delete,name="delete"),
    path('<int:pk>/edit/', views.edit,name="edit"),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/core/models.py
from django.db import models

# Create your models here.

market/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your Username','class':'form-control mt-1'}))
    password = forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'placeholder':'Your password','class':'form-control mt-1'}))


class SignUpForm(UserCreationForm):
    """ email = forms.EmailField(label="Email address",widget=forms.TextInput(attrs={'class':'form-control'})) """
    class Meta:
        model = User
        fields = ('username', 'email' ,'password1','password2')

    username = forms.CharField(help_text='<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>',widget=forms.TextInput(attrs={'placeholder':'Your Username','class':'form-control mt-1'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Your Email id','class':'form-control mt-1'}))
    password1 = forms.CharField(help_text ='<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>',label="Password",widget=forms.TextInput(attrs={'placeholder':'password','class':'form-control mt-1'}))
    password2 = forms.CharField(help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>',label="Confirm Password",widget=forms.TextInput(attrs={'placeholder':'enter password again','class':'form-control mt-1'}))

market/core/views.py
from django.shortcuts import render,redirect
from item.models import Category,Item
from .forms import SignUpForm
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request,'core/index.html',{
        'categories':categories, 'items': items,
    })


def contact(request):
    return render(request,'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('core:home')
    else:
        form = SignUpForm()
        return render(request,'core/signup.html',{
            'form':form
            })
    return render(request,'core/signup.html',{
            'form':form
            })
        

def logout_user(request):
    logout(request)

    return redirect('core:home')
    
    

market/core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Market Place</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="">
        <style>
            img{
                height:200px;
                object-fit:cover;
            }
        </style>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-lg bg-dark py-3 px-2" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand fs-3 ps-3" href={% url 'core:home'%}>SLUG</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                </ul>
                <div class="buttons d-flex">
                    <a href="{% url 'item:new_item' %}" , class="btn btn-dark px-4 py-2 ms-2">New item</a>
                    <a href="{% url 'item:items' %}" class="btn btn-dark px-4 py-2 ms-1">Browse</a>
                    {% if request.user.is_authenticated%}
                        <a href="{% url 'conversation:inbox' %}"  class="btn btn-success px-4 py-2 ms-2">Inbox</a>
                        <a href="{% url 'dashboard:index' %}" class="btn btn-secondary px-4 py-2 ms-3">Dashboard </a>
                        <a href="{% url 'core:logout' %}" class="btn btn-danger px-3 py-2 ms-3">Logout <i class="fa-solid fa-right-from-bracket"></i></a>
                    {% else %}
                        <a href="{% url 'core:signup' %}"  class="btn btn-success px-4 py-2 ms-2">Sign Up <i class="fa-solid fa-user-plus"></i></a>
                        <a href="{% url 'core:login' %}" class="btn btn-secondary px-4 py-2 ms-3">Login <i class="fa-solid fa-right-to-bracket"></i></a>
                    {% endif %}

                </div>
              </div>
            </div>
          </nav>
        {% block content %}
        {% endblock %}
        

        <footer class="container-fluid bg-dark text-white-50 px-3 pb-0 pt-4 d-flex justify-content-between margin-auto mt-auto">
            <div class="mx-4">
                <h4 class="fs-5 text-white mb-3">About</h4>
                <p class="fs-6">{% lorem 5 w random %}</p>
                
            </div>
            <div class=" mx-5 pe-5">
                <h4 class="fs-5 text-white mb-3">Menu</h4>
                <ul class="list-unstyled">
                    <li><a class="mb-1 text-decoration-none text-secondary">About</a></li>
                    <li><a class="mb-1 text-decoration-none text-secondary" href={% url 'core:contact' %}>Contact</a></li>
                    <li><a class="mb-1 text-decoration-none text-secondary">Privacy Policy</a></li>
                    <li><a class="mb-1 text-decoration-none text-secondary">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
        <script src="" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

market/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block content %}
<h1>Contact</h1>
{% endblock %}

market/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<div class="w-auto bg-secondary-subtle my-4 mx-4 px-5 py-5 rounded-3">
    <h2 class="fs-4 text-center mb-4">Newest Items</h2>
    <div>
        <div class="d-flex flex-wrap justify-content-between px-4">
            {% for item in items %}
            <div class="mb-4">
                <div class="card h-auto" style="width: 18rem;">
                    <a href="{% url 'item:detail' item.id %}" class='text-decoration-none'>
                        <img src="{{ item.image.url }}" class="card-img-top w-100%" >
                        <div class="card-body">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <h5 class="card-title text-secondary">${{ item.price }}</h5>
                        </div> 
                    </a>      
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="w-auto bg-secondary-subtle my-4 mx-4 px-5 py-5 rounded-3">
    <h2 class="fs-4 text-center mb-4">Categories</h2>
    
    <div class="d-flex flex-wrap px-4">
        {% for category in categories%}
            <div>
                <div class="card h-auto me-2 mb-2" style="width: 18rem;">
                    <div class="card-body">
                    <h5 class="card-title text-capitalize">{{ category.name }}</h5>
                    <h5 class="card-title text-secondary">{{ category.items.count }} items</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

market/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
<div class="col-md-4 offset-md-4 my-3 bg-secondary-subtle p-3 rounded-3 my-5">
<h1 class="text-center text-primary-emphasis">Login</h1>
<form  method="POST" class="my-4 " action="">
    {% csrf_token %}
    {% if form.errors or form.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Please Check the form again
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            
        </div>
    {% endif %}
    
    {{form.as_p}}
    <button type="submit" class="btn btn-success btn-md mt-3 w-100 fs-5">Log In</button>
</form>
</div>
{% endblock %}

market/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3 my-3 bg-secondary-subtle p-4 rounded-3">
<h1 class="text-center text-primary-emphasis">Sign Up Form</h1>
<form  method="POST" class="mt-4" action="">
    {% csrf_token %}
    {% if form.errors or form.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Please Fill the form correctly
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            
        </div>
    {% endif %}
    
    {{form.as_p}}
    <button type="submit" class="btn btn-success btn-md mt-3 w-100">Sign Up</button>
</form>
</div>
{% endblock %}